// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestPostgreWithEF6.Models
{
    public partial class Action
    {
        public int Id { get; set; }
        public string Titlear { get; set; }
        public string Titleen { get; set; }
        public bool Istask { get; set; }
    }
}