// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestPostgreWithEF6.Models
{
    public partial class Letter
    {
        public Letter()
        {
            Memos = new HashSet<Memo>();
        }

        public long Id { get; set; }
        public DateTime Createddate { get; set; }
        public string Createdby { get; set; }
        public int Sourceid { get; set; }
        public int Sourcetypeid { get; set; }
        public string Letterno { get; set; }
        public DateTime Letterdate { get; set; }
        public DateTime? Closedate { get; set; }
        public int Typeid { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string Tags { get; set; }
        public string Additions { get; set; }
        public int Destinationid { get; set; }
        public int Destinationtypeid { get; set; }
        public string Attachments { get; set; }
        public bool Confidential { get; set; }
        public bool Topsecret { get; set; }
        public bool Urgent { get; set; }
        public bool Alwaysontop { get; set; }
        public int Serialno { get; set; }
        public int Code { get; set; }
        public DateTime? Approveddate { get; set; }
        public bool? Isapproved { get; set; }
        public string Details { get; set; }
        public string Letternoen { get; set; }

        public virtual ICollection<Memo> Memos { get; set; }
    }
}