// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestPostgreWithEF6.Models
{
    public partial class Memolog
    {
        public long Logid { get; set; }
        public long Memoid { get; set; }
        public DateTime Createddate { get; set; }
        public string Createdby { get; set; }
        public string Message { get; set; }
        public long Letterid { get; set; }

        public virtual Memo Memo { get; set; }
    }
}