// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;



namespace TestPostgreWithEF6.Models
{
    public partial class Memo
    {
        public Memo()
        {
            Memologs = new HashSet<Memolog>();
        }

        public long Id { get; set; }
        public long Letterid { get; set; }
        public int Destinationid { get; set; }
        public int? Sourceid { get; set; }
        public int Destinationtypeid { get; set; }
        public string Createdby { get; set; }
        public DateTime Createddate { get; set; }
        public MemoMessage Message { get; set; }
        public DateTime? Replaydate { get; set; }
        public string Subject { get; set; }
        public string Actions { get; set; }

        public bool Urgent { get; set; }
        public bool Topsecret { get; set; }
        public bool Confidential { get; set; }
        public MemoReplayData Replaydata { get; set; }
        public int Serialno { get; set; }
        public int? Sourcetypeid { get; set; }
        public long? Parentid { get; set; }
        public int Eventid { get; set; }
        public bool Isreply { get; set; }
        public int Typeid { get; set; }
        public long? Replayid { get; set; }
        public MemeDetail Details { get; set; }
        public DateTime? Latestdate { get; set; }
        public bool? Isapproved { get; set; }
        public DateTime? Approveddate { get; set; }

        public virtual Letter Letter { get; set; }
        public virtual ICollection<Memolog> Memologs { get; set; }
        
        public virtual MemoAction[] MemoActions => JsonSerializer.Deserialize<MemoAction[]>(Actions);
        
    }

    public class MemoAction
    {
        public string Title { get; set; }
        public string TitleAr { get; set; }
        public string TitleEn { get; set; }
    }

    public class MemoReplayData
    {
        public string Body { get; set; }
        public MemoAttachment[] Attachments { get; set; }
    }

    public class MemoMessage
    {
        public string Body { get; set; }
        public MemoAttachment[] Attachments { get; set; }
    }

    public class MemoAttachment
    {
        public int Size { get; set; }
        public string Name { get; set; }
        public string Ext { get; set; }
        public string Path { get; set; }
    }

    public class MemeDetail
    {
        public int parentsourceid { get; set; }
        public int parentsourcetypeid { get; set; }
        public string sourcename { get; set; }
        public string destname { get; set; }
        public string parentfrom { get; set; }
        public object parentto { get; set; }
        public string fullnamear { get; set; }
        public DateTime letterdate { get; set; }
        public bool sourcests { get; set; }
        public bool deststs { get; set; }
    }
}