// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TestPostgreWithEF6.Data;
using TestPostgreWithEF6.Models;
using Action = TestPostgreWithEF6.Models.Action;

namespace TestPostgreWithEF6.Data.Configurations
{
    public partial class ActionConfiguration : IEntityTypeConfiguration<Action>
    {
        public void Configure(EntityTypeBuilder<Action> entity)
        {
            entity.ToTable("actions");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.Istask).HasColumnName("istask");

            entity.Property(e => e.Titlear)
                .IsRequired()
                .HasMaxLength(2044)
                .HasColumnName("titlear");

            entity.Property(e => e.Titleen)
                .IsRequired()
                .HasMaxLength(2044)
                .HasColumnName("titleen");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Action> entity);
    }
}
